lab:
  location: verizon 
  racks:
  - rack: v4n-200
    nodes:
    - name: node01ob200
      architecture: x86_64
      roles: [network,control]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["f4:4d:30:65:a1:78"]
      - ifname: eth0.203
        spaces: [data]
        mac: ["f4:4d:30:65:a1:78"]
      - ifname: eth1
        spaces: [floating]
        mac: ["8c:ae:4c:fd:c5:af"]
      power:
        type: amt
        address: 172.27.200.11
        user: admin
        pass: Password1+
    - name: node02ob200
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["f4:4d:30:65:a0:64"]
      - ifname: eth0.203
        spaces: [data]
        mac: ["f4:4d:30:65:a0:64"]
      - ifname: eth1
        spaces: [floating]
        mac: ["8c:ae:4c:fd:c2:47"]
      power:
        type: amt
        address: 172.27.200.12
        user: admin
        pass: Password1+
    - name: node03ob200
      architecture: x86_64
      roles: [compute,control,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["f4:4d:30:65:a2:62"]
      - ifname: eth0.203
        spaces: [data]
        mac: ["f4:4d:30:65:a2:62"]
      - ifname: eth1
        spaces: [floating]
        mac: ["8c:ae:4c:fd:c5:9e"]
      power:
        type: amt
        address: 172.27.200.13
        user: admin
        pass: Password1+
    - name: node04ob200
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["f4:4d:30:65:9c:d9"]
      - ifname: eth0.203
        spaces: [data]
        mac: ["f4:4d:30:65:9c:d9"]
      - ifname: eth1
        spaces: [floating]
        mac: ["8c:ae:4c:fd:ce:b8"]
      power:
        type: amt
        address: 172.27.200.14
        user: admin
        pass: Password1+
    - name: node05ob200
      architecture: x86_64
      roles: [compute,storage]
      nics:
      - ifname: eth0
        spaces: [admin]
        mac: ["f4:4d:30:65:9e:0d"]
      - ifname: eth0.203
        spaces: [data]
        mac: ["f4:4d:30:65:9e:0d"]
      - ifname: eth1
        spaces: [floating]
        mac: ["8c:ae:4c:fd:ce:cd"]
      power:
        type: amt
        address: 172.27.200.15
        user: admin
        pass: Password1+
    floating-ip-range: 172.27.203.100 172.27.203.101 172.27.203.102 172.27.203.103 172.27.203.104 172.27.202.0/22
    ext-port: "eth1"
    dns: 8.8.8.8
    public-api-ip:
    osdomainname:
opnfv:
  release: d
  distro: xenial
  type: nonha
  openstack: newton
  sdncontroller:
  - type: nosdn
  storage:
  - type: ceph
    disk: /dev/sdb
  feature: odl_l2
  spaces:
  - type: admin
    bridge: br0
    cidr: 172.27.200.0/23
    gateway: 172.27.201.254
    vlan:
  - type: data
    bridge: br203
    cidr: 192.168.100.0/24
    gateway:
    vlan: 203
  - type: floating
    bridge: br1
    cidr: 172.27.202.0/23
    gateway: 172.27.203.254
    ipaddress:
    vlan:
